{"name": "test_add_evidence", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_case_details.TestCaseDetails object at 0x0D2AB6B0>\n\n    def test_add_evidence(self):\n        driver = self.driver\n        self.login()\n        case_details = CaseDetails(driver)\n        home = HomePage(driver)\n        home.click_law_suit_page()\n        case_details.evidence_tab_entry()\n>       case_details.add_evidence_attachment_image()\n\ntest_case_details.py:49: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Pages.CaseDetailsPage.CaseDetails object at 0x0D2ABA30>\n\n    def add_evidence_attachment_image(self):\n        self.driver.find_element_by_id(self.add_new_evidence_btn_id).click()\n        self.driver.find_element_by_id(self.add_new_evidence_file_btn_id).send_keys(self.FILE_PATH)\n        time.sleep(2)\n    \n        img_list = []\n        source = self.driver.find_elements_by_tag_name('img')\n        for image in source:\n            img_list.append(image.get_attribute('src'))\n    \n>       assert self.driver.get(img_list[1])\nE       AssertionError\n\n..\\Pages\\CaseDetailsPage.py:124: AssertionError"}, "start": 1568408818028, "stop": 1568408834171, "uuid": "85e9fa3b-4523-4c08-bded-8e6b2a10019d", "historyId": "1b0719228033f564f68e8171fe6bf095", "testCaseId": "b97ef1dc24e3a37bb3c5fd0020ba1941", "fullName": "test_case_details.TestCaseDetails#test_add_evidence", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_case_details"}, {"name": "subSuite", "value": "TestCaseDetails"}, {"name": "host", "value": "EVT01066NB"}, {"name": "thread", "value": "12388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_details"}]}